### ISSUE TITLE
Why don't download these files as a ZIP?

### ISSUE THREAD

**Issue by aleff-github** [SHUR1K-N/Flipper-Zero-Sub-GHz-Jamming-Files#4]
Hi, I read this line in the README file but I don't understand why it happens--what is the problem?

`DON'T download these files as a ZIP or use git clone. You have to click on each file here, then right-click on "Raw" and then "Save as link" or else you'll have parsing errors.`

**Comment by aleff-github** [comment]
And, what do you mean by `Save as link`, just save the raw text or something else?

**Comment by SHUR1K-N** [comment]
In the previous version(s) of the SUB files, saving them in any _other_ way would cause parsing errors on the Zero; probably due to some encoding differences or the way blank spaces are dealt with while saving using different methods.

In the latest version though, all these methods _will_ work:

- Downloading as ZIP
- `git clone`
- Downloading as raw file
- Saving link on the raw file
- Copy-pasting the content into a text document and changing the extension to ".sub"
